services:
  tgbot:
    build: bot
    environment:
      ML_SERVICE_URL: "http://middleware:8090"
    env_file:
      - bot/.env
    image: "anuiel/anuielbot"
    ports:
      - "8090:8888"
    container_name: "tgbot"
    command: ["python3", "main.py"]
    depends_on:
      - middleware
  middleware:
    build: api
    image: "anuiel/nginx"
    ports:
      - "8091:8090"
    volumes:
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - face-upscale
  face-upscale:
    build: face-upscale
    image: "anuiel/gfpgan"
    ports:
      - "8092:8090"
    container_name: "gfpgan"
    volumes:
      - ./weights/face-upscale/RealESRGAN_x2plus.pth:/usr/local/lib/python3.11/site-packages/weights/RealESRGAN_x2plus.pth
      - ./weights/face-upscale:/home/GFPGAN/gfpgan/weights
    command: ["python3", "run.py", "--port", "8090"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  deblur:
    build: deblur
    image: "xiryss/deblur"
    ports:
      - "8093:8090"
    container_name: "deblur"
    volumes:
      - ./weights/deblur/motion_deblurring.pth:/home/deblur/Restormer/Motion_Deblurring/pretrained_models/motion_deblurring.pth
      - ./weights/deblur/single_image_defocus_deblurring.pth:/home/deblur/Restormer/Single_Image_Defocus_Deblurring/pretrained_models/single_image_defocus_deblurring.pth
    command: ["python3", "run.py", "--port", "8090"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  lowlight:
    build: lowlight
    image: ""
    ports:
      - "8094:8090"
    container_name: "lowlight"
    command: ["python3", "run.py", "--port", "8090"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
